name: Examples Deployment (Heroku)

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add remote origin
        run: |
          git fetch --all --unshallow
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy to Heroku Main
        run: |
          git push heroku HEAD:main -f
