name: Node.js Package

on:
  push:
    tags:
      - 'v*'

jobs:
  get-npm-version:
    name: get-npm-version
    runs-on: ubuntu-latest
    id: package-version
    uses: martinbeentjes/npm-get-version-action@master
  publish:
    needs: get-npm-version
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run copy-to-dist
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: echo "Printing current version:"
      - run: echo ${{ steps.package-version.outputs.current-version}}
