name: Node.js Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: get-npm-version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run copy-to-dist
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: echo "Printing current version:"
      - run: echo ${{ steps.package-version.outputs.current-version }}
